---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-config
  namespace: monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "kuma-config-dst"
  resources:
    requests:
      storage: 8Gi
