apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repo-secret
    namespace: redbot-test
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JGPxsVPncJeeNKL6GR+i+ErBSQ==,iv:6lhrEKjwh5AuxV9y2BDxI5vzyf9RJa2/fv4zDBaO4CU=,tag:GPuPy69d7na2PCr7dI2TWg==,type:comment]
    #ENC[AES256_GCM,data:ghgrtdkF8h4tF7fbcgYTHwEJJavS55a7GCiS88K3,iv:0vOa9jlWatk4Pg+fC1qGGkV/GU3F7y49JJ+9bx+lsE8=,tag:EXXg3BOaDynUpdlR3kIW0g==,type:comment]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:lmM4czkKlkPuVTaiGWIy9sXErwmQ8dSFssIRhaHF3K3rQuZnhkr6fkDKxc3HINlF8t4=,iv:f9uqmpjt/eIRLpAprpv4HqIxrztqNvWEKKIaRCoCRn0=,tag:OHQS4zP0OqHObZcf0vuk7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VyszN1BLSml0TnhhaVMv
            TU1WRy9WS0sybGdablhCaDVYQXZ4eHR4Q0ZRCnlqSmpZUnMwN1hhWmxlTEJ3bU9Y
            U0dMODJFRGFBek9qb2puenp0Y09JV1UKLS0tIGpqNnNEcllwb1YrRm1rR1hUR1pC
            anBNa0JmWVc1Nkhsci8vamZ5MFNIREkKm1peUbQcsKWt4mhQlIVTMCQlKSZsLogm
            8OfPTxgz1EWbk4BQOfpYkU4jHb8lvGXAkZXepNdpCvh1xsaIbwyLxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T04:59:16Z"
    mac: ENC[AES256_GCM,data:IyPZypJqgEnUvDY3WZWi1RtTSDtcNWqI/VOeWboMZpe4qWOwg3CTxfK5mUhpl8C6UdUlJWzIIC98xVpJzmrL8hYkDhQRD3epSeSRk/xlER/5emjY2rYMfchjPlQwVZf17pTdD98gJ/LSa0j2gry4LjoX1m/apSOeU2qGXuM0Hv0=,iv:S5StaN1dcTONBAUwSiDbNOmoZ7fzgl4hTUm6dZOYMlg=,tag:ON8WKXgiWPiUQbyAzWW8nw==,type:str]
    version: 3.13.1
