# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: latest@sha256:095e6d410d1d27b17cc4a961a9bab9fab5ffce6e49389d8ec685f65ab5538525
            env:
              TZ: America/Chicago
              JELLYFIN_PublishedServerUrl: https://jellyfin.${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 100m
                memory: 2000Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &jellyfin-port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *jellyfin-port
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:jellyfish
        hosts:
          - host: &host jellyfin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: external
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config
        retain: true
        globalMounts:
          - path: /config
      plugins:
        enabled: true
        existingClaim: jellyfin-plugins
        retain: false
        globalMounts:
          - path: /var/lib/jellyfin/plugins
      media:
        enabled: true
        existingClaim: media
        retain: true
        globalMounts:
          - path: /media
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /config/cache
