apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyfin
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:gJY4VwAgqiOujcMQ8ljYdEiXDQ==,iv:+NvbzzoZkbmCJsucQJoog7C0yc9PEXAp17DW/4i30sI=,tag:Z0QiyiXfmYTHA19nQQBj3g==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:ngO+UL1BDNKHDuJkOZzwPDmy5ns6c6nD2wO3Ar4BwR+j8LfsHjGg2i+ImyMRLmMxd7u5JHHi1w==,iv:icDVI6CowNc5ldGeCjVpZME8rPtDwL+GRN93MZKUK60=,tag:fkYWrSbDoPpkpJX5hmbxHw==,type:str]
    #ENC[AES256_GCM,data:DVhrhPmkPW9H+mSpXmA83clsARKswtxuqegfofCk,iv:Vax9m6wz9E9i5aeOufqemfPKOvjMEr6t7WW/jmZTFQI=,tag:CejhHU3NRUFPp9G+s8wIQA==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dcWg7YxXXYW97mtziNFJ4K1NRnE5al+fz+KJQKGADjeq6wT406XVuDRQWXgNtyNznrk=,iv:+veKGBBOlzeU1hBsBMSAsI8miVBC4kEjxWjukRTjxc4=,tag:kgPgCyeXnXOkcDr0Jw4M4A==,type:str]
    #ENC[AES256_GCM,data:BTI8RfkanijvmEmypsULOMYVJAalPkZ6yiBHSTR2FjyrwD86EAumgwI=,iv:KRD2ihAY600pFFrNK5TJZEGib7YveCN4GdqgUAekm7Y=,tag:7xWfnaE0QEB3mKicb/KDWQ==,type:comment]
    #ENC[AES256_GCM,data:oWivN28iDTZKEUdSIPTEdTfxyzNYhtrpotHtbMqB95JHCX2kpv+mPmoEnkUE3DC/y6NDdnbpQSkWuYx4k07DHTd3VKHatw==,iv:ygeJsZEgolnBOLITOp7f/MstLOMcvOE9aJYo9S6Ozoc=,tag:qTqOYdSrsb0hBOjIYsPfHQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Kryvl6hwDAtEjjcQdrJ+vA==,iv:sPKPTkK345YSVO3CrD5Qi0eeVBlmYSB1cqzad+4zivM=,tag:U5oYV68g7fS6+4q3pUzrOA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:y0YUTFdlcai5k0xrm1wxGBiZq+jkXJUJdXUI5a4EnZE=,iv:YnO6CBsfcTlDfTTLpjimTh32Hu1J2hVVXNm7A4IIs6M=,tag:NWrGz90zcLWmYkbGQetuEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TzVNRFZXUHQrU3FjaEdm
            TTRyYnp2a1lMaHQxaWpudkQzTExIS00xdzFzCkp2UUdobzVpSm0xUEt2U3BJODVB
            WlZqMXVvU1YxanlnV3FRblc0cUUrcFUKLS0tIDVvK01lais1MkRDUXFmTDdSRU1o
            QklpbHVOY0NkdjZoQzZJbUFMQWVyS1kKMTJF7upAeR9K5sqheraxUc1s89BQvvrJ
            uprEMPYtiMfUCCqKiiEog7uPSdIjcjsE/oQ/U10J0BxvMKMF4itCVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T20:54:30Z"
    mac: ENC[AES256_GCM,data:PMv/EIxadap53aoltvstvm1vvHJO2f03AdAYYqJh4vM7+bI8Xh2AkXY5IcqlwjKPtVp9/OgCf/C5jas/mwZ0Cdqe8I6+omukQp7QuNV6Weukp+9GYeQrhrEViZhaySnQa7N/LwCffz083/cXBkCtDW0QHiKCHgqnRHwd/U9Sze0=,iv:jd/i3A4N9/cSEE3E7M7unANyLVhPokiGMdkP0a3l3y0=,tag:wD7oHJu22b3vGirJVyddTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
