---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: jellyfin
  namespace: default
spec:
  copyMethod: Snapshot
  mover:
    cache:
      capacity: 32Gi
      storageClassName: local-path
    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
  repository:
    kind: ClusterRepository
    name: backup-target
  retention:
    keepDaily: 7
    keepHourly: 24
    keepWeekly: 5
  sources:
  - pvc:
      name: jellyfin-config
  volumeSnapshotClassName: csi-ceph-blockpool
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: jellyfin
  namespace: default
spec:
  policyRef:
    name: jellyfin
  schedule:
    cron: 0 * * * *
