---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-pve-external
  namespace: rook-ceph
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v19.1.0
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  monitoring:
    enabled: true
    externalMgrEndpoints:
      - ip: "10.0.10.103"
      - ip: "10.0.10.102"
      - ip: "10.0.10.101"
    externalMgrPrometheusPort: 9283
