apiVersion: v1
data:
    admin-secret: ENC[AES256_GCM,data:vs+2Xcc6aviZV0m+U8Ifng==,iv:vISNrOd0IL9OVaRDBZhcOdJfhsAPA6tS2RGyWp7l8/0=,tag:F7aWguQ9lS+uaPP0YPWkTw==,type:str]
    ceph-secret: ENC[AES256_GCM,data:uDBDksvvMNXToc0kBkTksvnetpM7ZZ2fdMVjVD1/MFQSa7PUP2u+4kTyVrSd/yS4G02IQIUL+dI=,iv:TSVxdbaxYYivPchZ/5xl043ujp+vY1bGOJb/ytho7K0=,tag:CsP1wjF0RC+xUCPZ6J5ypg==,type:str]
    ceph-username: ENC[AES256_GCM,data:LNNTHr+Mg14G2549IqXXpOP1t1ey6leqH2wruw==,iv:gsMnSZ8uad8rsqDZsH8OJ+1vbltI1HhQArkBNbXgWMw=,tag:R6SBctnAjRFhLvyU6ENprg==,type:str]
    cluster-name: ENC[AES256_GCM,data:rCAPopdTO/MjZkFB,iv:j44ROOKXI+Jvk2QWxuUpRaD0TIZw0Jb5U2B5XF44oOQ=,tag:YySwn1aQ/c8DUvk2d96oFw==,type:str]
    fsid: ENC[AES256_GCM,data:3K8mgNEVmt4GFEnd+Z2VTaaJ0wEu8fGE1YwgqNBixGT7ARaaxk0KA1ThJDpaPpxa,iv:Lamcw5pKsviFGL81AkYvqdkIVr/nqHSmyzlQ9pXiE1k=,tag:QJgFCLoO1pAuKwU/dDY1Ew==,type:str]
    mon-secret: ENC[AES256_GCM,data:3QgGLZseeOfE29HpW8QyYw==,iv:wWL7nk/ZKZiC8edPkdxY48zyrcL2qZC38YUWfOYulXU=,tag:PGrnycwFYdsDaGuRdPaFUA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-ceph-mon
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmZBQjV1QUk4T3BiY2Jl
            MU1HQW9yZ1lKK1lHdTQ2cFdEb2F3bnpUalFnCjdSMnA4RGQzQ2lwNjVaQ2tsTTFz
            eDFiN3YrVnluQTk4MldRTnB4Tnk5M0UKLS0tIG1kZDhXR3l2MzFiWUFjTWRmMlQ3
            cGd5MXY2a3BGYmNBcnIyUENDUTZoMTQKSQ1IP9IPqAk9iayWLK7cF71vYGTnoRY/
            3Bo98qoEo+ZG6rwt4LAEyIzZCbyqnQOS6sdfsdRSx0fCXcoe+1IWLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T18:40:16Z"
    mac: ENC[AES256_GCM,data:nQSUgbBIWb5m57rSXv6VhKuwkTOXXszDCCE60rpvbIcyAhc+ZdBb7lFZ7zZXW+BvJ/K0fM04zHpoS79bwG1eov9TTsEWWDzfDIx9GVO/8p6CUiPbMFN14LQ2MiOqUfulpGuS3Uc3T20C/fsX7rUzaIsRCoPIp8ZJf7L58rAadVM=,iv:eOH4lkZfY5kfZxE91CBFs/oIDABiyg85y6GGdOYN+mA=,tag:EIR7oMyyAHMKkhUVjobzoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    data: ENC[AES256_GCM,data:sCJgwHNwBNm4EXt3qogV6S70Kd13MgL1cjE=,iv:yF72M2tPeELGdFtd08JIf3nsCtspfjzkQ9aFMTtqkJ0=,tag:KD3vK281b/DOwuud1iu3mA==,type:str]
    mapping: ENC[AES256_GCM,data:hqU=,iv:1/qSvxJu//fZULGH6RUtLODf0URU0vHDTbHDEoZr3i4=,tag:pi2GtQruBGUlFZABKZmYIw==,type:str]
    maxMonId: ENC[AES256_GCM,data:QA==,iv:okngIqyjynuVDSCncdfzmZKm79ki//INpsA5/QNEOF0=,tag:C+JNYVMU95QakLd9qodCNw==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: rook-ceph-mon-endpoints
    namespace: rook-ceph
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmZBQjV1QUk4T3BiY2Jl
            MU1HQW9yZ1lKK1lHdTQ2cFdEb2F3bnpUalFnCjdSMnA4RGQzQ2lwNjVaQ2tsTTFz
            eDFiN3YrVnluQTk4MldRTnB4Tnk5M0UKLS0tIG1kZDhXR3l2MzFiWUFjTWRmMlQ3
            cGd5MXY2a3BGYmNBcnIyUENDUTZoMTQKSQ1IP9IPqAk9iayWLK7cF71vYGTnoRY/
            3Bo98qoEo+ZG6rwt4LAEyIzZCbyqnQOS6sdfsdRSx0fCXcoe+1IWLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T18:40:16Z"
    mac: ENC[AES256_GCM,data:nQSUgbBIWb5m57rSXv6VhKuwkTOXXszDCCE60rpvbIcyAhc+ZdBb7lFZ7zZXW+BvJ/K0fM04zHpoS79bwG1eov9TTsEWWDzfDIx9GVO/8p6CUiPbMFN14LQ2MiOqUfulpGuS3Uc3T20C/fsX7rUzaIsRCoPIp8ZJf7L58rAadVM=,iv:eOH4lkZfY5kfZxE91CBFs/oIDABiyg85y6GGdOYN+mA=,tag:EIR7oMyyAHMKkhUVjobzoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:hspPiZslb3EWY68vckybqw==,iv:LQqkTaXxmM4IFBPYUjrdewDZz/xNBkH3NehlDgG1o6w=,tag:wv7vAJrjToSHoIukHhgWLg==,type:str]
    userKey: ENC[AES256_GCM,data:lQm5I7eIX2prPUv3xm/f981uJtLZGrRGNVUh47mx48LVfzpYchgBnPtht5rb5+LbopG0ua2h1O0=,iv:T2AxqNCqo792DRNNzxuMqyJuJ5pFAg3isdCUxFfimVo=,tag:NlUD/u/MeESlX0UHJ2SnQw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmZBQjV1QUk4T3BiY2Jl
            MU1HQW9yZ1lKK1lHdTQ2cFdEb2F3bnpUalFnCjdSMnA4RGQzQ2lwNjVaQ2tsTTFz
            eDFiN3YrVnluQTk4MldRTnB4Tnk5M0UKLS0tIG1kZDhXR3l2MzFiWUFjTWRmMlQ3
            cGd5MXY2a3BGYmNBcnIyUENDUTZoMTQKSQ1IP9IPqAk9iayWLK7cF71vYGTnoRY/
            3Bo98qoEo+ZG6rwt4LAEyIzZCbyqnQOS6sdfsdRSx0fCXcoe+1IWLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T18:40:16Z"
    mac: ENC[AES256_GCM,data:nQSUgbBIWb5m57rSXv6VhKuwkTOXXszDCCE60rpvbIcyAhc+ZdBb7lFZ7zZXW+BvJ/K0fM04zHpoS79bwG1eov9TTsEWWDzfDIx9GVO/8p6CUiPbMFN14LQ2MiOqUfulpGuS3Uc3T20C/fsX7rUzaIsRCoPIp8ZJf7L58rAadVM=,iv:eOH4lkZfY5kfZxE91CBFs/oIDABiyg85y6GGdOYN+mA=,tag:EIR7oMyyAHMKkhUVjobzoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:vpiU1/MH6Anjwac978te2GQ6ua9mEdSOTcDeug==,iv:JGmFQ8SVVcO4SvSRt+LS3lbxF8KgBoFg4xojG5odoNk=,tag:vRnFXBIFzNjHtM6xVlpNCA==,type:str]
    userKey: ENC[AES256_GCM,data:Ss01L6poPkZCoMDnGamCJfMpH3PNBKDTkZIPszSbGgvsu1NU9P5D7O9rkAHYU+VDn9GKuQX5MhU=,iv:GE83FNVFZCN5LAo0SiHz0dAQSqer0VGOsVQOv8vOgUw=,tag:CFzbDhxooIyQQW8cgoF39g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmZBQjV1QUk4T3BiY2Jl
            MU1HQW9yZ1lKK1lHdTQ2cFdEb2F3bnpUalFnCjdSMnA4RGQzQ2lwNjVaQ2tsTTFz
            eDFiN3YrVnluQTk4MldRTnB4Tnk5M0UKLS0tIG1kZDhXR3l2MzFiWUFjTWRmMlQ3
            cGd5MXY2a3BGYmNBcnIyUENDUTZoMTQKSQ1IP9IPqAk9iayWLK7cF71vYGTnoRY/
            3Bo98qoEo+ZG6rwt4LAEyIzZCbyqnQOS6sdfsdRSx0fCXcoe+1IWLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T18:40:16Z"
    mac: ENC[AES256_GCM,data:nQSUgbBIWb5m57rSXv6VhKuwkTOXXszDCCE60rpvbIcyAhc+ZdBb7lFZ7zZXW+BvJ/K0fM04zHpoS79bwG1eov9TTsEWWDzfDIx9GVO/8p6CUiPbMFN14LQ2MiOqUfulpGuS3Uc3T20C/fsX7rUzaIsRCoPIp8ZJf7L58rAadVM=,iv:eOH4lkZfY5kfZxE91CBFs/oIDABiyg85y6GGdOYN+mA=,tag:EIR7oMyyAHMKkhUVjobzoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:YpmERf5wezR6gc6Er3aLE7KrHRw=,iv:FFcM6svtEW99i1+9bCC8CpCM6D3MZtsenwRKhU/OdVQ=,tag:udP/uehLyC3aWGIPkUx0uA==,type:str]
    adminKey: ENC[AES256_GCM,data:7/2BqGSy9icLwJd7tTSTZr+DSfSJzrWR6rQCJWMuS5fkcVPt5v2cN9xRh5fggpMughiRJ5/5O34=,iv:GKKaKtwPLPPmgT6Mc+DlAg8uxS+TU28G6dO9JgDaezE=,tag:rWDjzVbRSee3Zhdt/zUIpQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmZBQjV1QUk4T3BiY2Jl
            MU1HQW9yZ1lKK1lHdTQ2cFdEb2F3bnpUalFnCjdSMnA4RGQzQ2lwNjVaQ2tsTTFz
            eDFiN3YrVnluQTk4MldRTnB4Tnk5M0UKLS0tIG1kZDhXR3l2MzFiWUFjTWRmMlQ3
            cGd5MXY2a3BGYmNBcnIyUENDUTZoMTQKSQ1IP9IPqAk9iayWLK7cF71vYGTnoRY/
            3Bo98qoEo+ZG6rwt4LAEyIzZCbyqnQOS6sdfsdRSx0fCXcoe+1IWLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T18:40:16Z"
    mac: ENC[AES256_GCM,data:nQSUgbBIWb5m57rSXv6VhKuwkTOXXszDCCE60rpvbIcyAhc+ZdBb7lFZ7zZXW+BvJ/K0fM04zHpoS79bwG1eov9TTsEWWDzfDIx9GVO/8p6CUiPbMFN14LQ2MiOqUfulpGuS3Uc3T20C/fsX7rUzaIsRCoPIp8ZJf7L58rAadVM=,iv:eOH4lkZfY5kfZxE91CBFs/oIDABiyg85y6GGdOYN+mA=,tag:EIR7oMyyAHMKkhUVjobzoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:dHNtcRM5Apx6ae0rjZS9Gl1gnOttwXkWzuTfWw9ar0A=,iv:2Y3wJylV0PS3KK3JjyBHnk2wHBOpo617WhEjfOmD1j8=,tag:AaIwb150k3Besnbr6EIXTQ==,type:str]
    adminKey: ENC[AES256_GCM,data:yf7HEY0nzHr/EoYqKeKOb3bH+HvD+v7rqlERmgmvMB3qdrxfXeWJeHJC8FT3MOHdrXivaTTTZE4=,iv:q9lLpBpRNPZI50A3S0ruv+tP67EcdgtcRGu7CDGPFfk=,tag:VNjWTyNRio7BMjIUq2wfHg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmZBQjV1QUk4T3BiY2Jl
            MU1HQW9yZ1lKK1lHdTQ2cFdEb2F3bnpUalFnCjdSMnA4RGQzQ2lwNjVaQ2tsTTFz
            eDFiN3YrVnluQTk4MldRTnB4Tnk5M0UKLS0tIG1kZDhXR3l2MzFiWUFjTWRmMlQ3
            cGd5MXY2a3BGYmNBcnIyUENDUTZoMTQKSQ1IP9IPqAk9iayWLK7cF71vYGTnoRY/
            3Bo98qoEo+ZG6rwt4LAEyIzZCbyqnQOS6sdfsdRSx0fCXcoe+1IWLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-03T18:40:16Z"
    mac: ENC[AES256_GCM,data:nQSUgbBIWb5m57rSXv6VhKuwkTOXXszDCCE60rpvbIcyAhc+ZdBb7lFZ7zZXW+BvJ/K0fM04zHpoS79bwG1eov9TTsEWWDzfDIx9GVO/8p6CUiPbMFN14LQ2MiOqUfulpGuS3Uc3T20C/fsX7rUzaIsRCoPIp8ZJf7L58rAadVM=,iv:eOH4lkZfY5kfZxE91CBFs/oIDABiyg85y6GGdOYN+mA=,tag:EIR7oMyyAHMKkhUVjobzoQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
