apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000]
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
      # -- image repository
              repository: ghcr.io/onedr0p/sabnzbd
      # @default -- chart.appVersion
              tag: 4.4.1@sha256:4188d3c29c53de1018edcfd5dc2d0a0c7955b9a239b91ff6c859626abd3494dc
      # -- image pull policy
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            env:
              TZ: America/Chicago
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd, sabnzbd.default, sabnzbd.default.svc, sabnzbd.default.svc.cluster,
                sabnzbd.default.svc.cluster.local, sabnzbd.${SECRET_DOMAIN}
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 8000Mi
    service:
      main:
        enabled: true
        ports:
          http:
            port: &sabnzbd-port 8080
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:download
        hosts:
          - host: &sabnzbd-host sabnzbd.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *sabnzbd-host
        className: internal
    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
        retain: true
      downloads:
        enabled: true
        existingClaim: media
        retain: true
        globalMounts:
          - path: /media
