---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: Restore
    apiGroup: kopiur.home-operations.com
    name: sabnzbd
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads
  namespace: default
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs
  resources:
    requests:
      storage: 1Mi
