apiVersion: v1
kind: Secret
metadata:
    name: bazarr-secret
    namespace: default
type: Opaque
stringData:
    BAZARR__API_KEY: ENC[AES256_GCM,data:JbOAhz4ayyYTgO0qUaujuHPe0DQrbQSb04saVjTFroQ=,iv:iLDsOuMyGj4re3loE0b8doAiRdqlmiQBx4NADPkzM34=,tag:mLf5ntBYyV4ByM6Ku97bsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZFFCalZZdG13cDVnVUZM
            d1VVODErODNhdjV3V0VmWlhHS2V2WElReXcwCkJWVjVINGFaeXVmS1hzeUd5WVdu
            cklWRXNKdnltUmNGcTR6UnBlRFlUTmsKLS0tIEJxQ0FNTHd5Y0VrMUkrcms2Q2xn
            ajhRYXpPNWxpUzVkNlJVL2JoWlg2MmcKyw8Sz+pShf5PavyZIPdswgUMr8ig7n6U
            rQck8vd/EqwOfhNnqS+c9O+NlNexUgQe9M7ovinlHqUCneZNXE6qpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-13T21:28:25Z"
    mac: ENC[AES256_GCM,data:fnoqKFVd+GXldxMujabv7ywlU+T2EPmKRQMZ0LJ/k2TzT2R1EUUkAVoxisJ6qiUo8o02keXsdaOlCpQ8CSLQr5B4NqhkWFHpICrJ/NLl/0EJLdlbI74AJSP57voyqtnnZ9j4rlddRsBxT4H3s1Y1FegsNgEufrUdK+9Led6x3xA=,iv:rCCzyI/IbCNFP7a2ee3ZuqRk3iHr1rwnx733L8kvDvA=,tag:q7s9DwsBGrtcDLIk/gHgyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
