---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: bazarr
  namespace: default
spec:
  copyMethod: Snapshot
  mover:
    cache:
      capacity: 8Gi
      storageClassName: local-path
    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
  repository:
    kind: Repository
    name: backup-target
  retention:
    keepDaily: 7
    keepHourly: 24
    keepWeekly: 5
  sources:
  - pvc:
      name: bazarr-config
  volumeSnapshotClassName: csi-ceph-blockpool
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: bazarr
  namespace: default
spec:
  policyRef:
    name: bazarr
  schedule:
    cron: 0 * * * *
