---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-anime
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "bazarr-config-anime-dst"
  resources:
    requests:
      storage: 8Gi
