apiVersion: v1
kind: Secret
metadata:
    name: restic-config-bazarr-anime
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:LjRQAZSPvl/IPnT+46B/ESP4Rw==,iv:oEHy8EkrhZccuGvkN4+ghhqsaSfQG6i1wKukF55uXMg=,tag:PY/J7zTfnAcGfKu0jVYHdQ==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:1hjFmSixrvt/EfZPFhCAOvZGjLclsziBRDXGKWKux40wyVXAcARZ7J/ppszCDHiViD5d+db0cXKRJN8=,iv:uI7QJN+sKQVKT6DNYV+ffBuqq0+k9HPz0w0V1n9/O7A=,tag:HMA19+7ukaS8f5c92TuQcw==,type:str]
    #ENC[AES256_GCM,data:Hwuq1QoKrRN2KGcIKwuD5uweLTAqwM0KTmWf0Bqa,iv:0DugshO7xsrUkn5qMopHuRqx9u0IVDwuelSnrCpU9pI=,tag:q1mH1Ahbxrv5mT2Ei4JELA==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:EV0qjxChh9ydvZvTLvoKDnehQ+p9qAm2K+31xu/OgJ/Mb9Q/191NYV5wEkCS5OYKF3s=,iv:e18KNQQv+OSdIDhAnjEBF9za2I1KUkorSJMnJhojW88=,tag:lLuhc9umhr67m3TXMPYHGw==,type:str]
    #ENC[AES256_GCM,data:VnNwQ9KWqwilWw+njDffdJBuoeGKrpkHXwl0Y1UASEUr0mFQr/HFsLE=,iv:ID5B7W8Cv0lPau85/t5HtyHI8mqJWDgqs52GdMUiDYQ=,tag:IHyOLoLZOEvPoXae/FQNHg==,type:comment]
    #ENC[AES256_GCM,data:srHuLNFn2Z5cBtFl0pgVyBJ1xjPoF510GadkluNXM09vQ67OwfT9M8K4/GWhpJ218mBQ2ammLhLwFjrnFlxBcepTpHr1bA==,iv:WecuUOhR0+EgScIb7YLwAdRIHYNs4+K6b+xDVwXVg7s=,tag:LhFiOBJ1s2fFQn5wY7ZM8Q==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:MSKV0Z+SVyvrUWwq0nLjVw==,iv:LJTiJkr42V64BtxCFiNS4MmT+i1YNTqs2aou6z+wWk4=,tag:zNdtbRg0KvTL1698DA0LYQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:75q4MO4eyu+iWgzy/9hFz2nvHPmDqYdbQOynznZOgxI=,iv:8rz7l3SUKvdD9ki2+WFV52LI5y4t/I8OyS+9aG5DN0M=,tag:yLE7RgKQPmOq+5urxmclpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2pYTGxOSGtvR2VGM0Vi
            L3ZlRUJiSjRDNkdhcTEvRC8yRllOZmY5azJvClB1ZElaR1hvclU1dDZ5NzV2MmN5
            WVAwNEpVYW53MDlQVEpUdDZiVjRGWWMKLS0tIFpJYXpRbEsrelJtSDNFeVNVTzdy
            cnJ1QXV3NW5rQm9qeDBEUlNvNWpoNFkK5+GYWo7WsJ1pPcml8Qs89JmH84DbLsWe
            tEP7/76JQFeSThN/JQGMJ3ytjCyJ4K90DrjOlM23+PWoU7+qXjCJZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T08:07:12Z"
    mac: ENC[AES256_GCM,data:uG2/dcTJa+XZ5r+RNE4u4mKCgbxpeB3PCCoXBberdmOQLv/GwvoXgHbieCt8qNg9RectbPfJsI/rWyBbkEIdVlf4cAgo7xqegSBIxvxfV0vbeAmoRzQ5F8Bmy+dAi33C/RoRqZoTGQbi/XxgYUW0T1Sv9KobSiGvGtZxtw2bueg=,iv:NeFxag6vtB1Mu5DicpuZJXYXtJBFXbYSJupXRJSAuE8=,tag:WApbF7hRmH7Gd0oxhf8yGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
