---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.9.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    loki:
      enabled: true
      isDefault: false
      # persistence:
      #   enabled: true
      #   storageClassName: local-path
      #   size: 5Gi
      rbac:
        pspEnabled: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
    fluent-bit:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      enabled: false
