---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-loki-stack
  namespace: monitoring
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  resources:
    requests:
      storage: 40Gi
