ansible_become_pass: ENC[AES256_GCM,data:6TZF05/NkRU7,iv:cJxhEfD8yByeGyLbsAuqX7uwdzroEmRG4HPbboUspZ8=,tag:BW0XtqvebJvsYyMhnaZVsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2WlJhN2pOb1RLeTJBQS93
            NTBVTkNoZ1RYazhObWM2NjBPTExPRkk2QURvCjdFSjN1NklTMkZiemxkZTZnbEFq
            NkxJNkRQT3BiTG04d1o5MlpYVkl1UU0KLS0tIEJDZ01YczhObGpBN0t2NldNWmxR
            amdNWFBDdko3TFRaeWVRUE9sdGdWWWsKkKkVL583GE9jldckLCrF7jYXN5CWcVr0
            L7pU618V6oMicBUkfyWHElZfE47Cw3Q8vchIlokg2ROAlq+VxVOTRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T19:12:30Z"
    mac: ENC[AES256_GCM,data:cuVUP1oiFk/IemLMePynbYEsveL7sxkidVegjYRCnNoldysY3VymPT4JF6FGo7aPG+VgfsftSQ1QTfRhuvkFP3Y2jt7+zm8DwiS+x9GqeovSRGC478i+9is4lGtjHXrSEYsOW/8c3QfAVnaoVwiwq4rV+TK5iMftGz8bhpucjJM=,iv:IfIzZAOKEiQ+x5eAG8d59K59G9jFwuUn1duMf+TrA9U=,tag:UvvAG3ekZG41HH8aGGg07g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
