ansible_become_pass: ENC[AES256_GCM,data:4ozK96e7rTwZ,iv:ycebIzHxyh46gBeLUSvs+THCEztvTh1mH6dMXz+1ddU=,tag:HRpToKCLfRPtNfGopnC5FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZFBmeWNsMnFJd3A0MjJ0
            SlRDSXNTcFlCUmIxMzVwQ1ZYUXJpUytQSVhvClgyWGI4MFJjK3JZdTkwcUlCRkNZ
            WGJKbnkva3NrQmhkcFJUWU4xSHJodmcKLS0tIHMrbk1uempvT0FMTXBHNzlPUlZa
            NkNOeG5sMFE1WkZXdHVULzFWOVNyNEEKTUnjP+yi2TovTGq4oedsFGYlcvcDY7cT
            2gCptHYvtIGsqkm0sZgjUTRxUvxewbL3lLtwSEaXMqrOnAjcXcgo7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T19:12:31Z"
    mac: ENC[AES256_GCM,data:WccHQtjKi3X1ULef5KhQZlWeCBVNgISncp/MvP4U8mIG3GSNPcxiFqCpbSsLzJTI1WBds+84AfiEkT5+Q95yBDX+1yEpb5nPsIf/aRcoUTNjprLet54UMf5kXcedmYETRPjBe+dwKMR0mkYKefD2oaooRoauI2ntSZWLDkCMLHY=,iv:JjEOeumgc/fIIDT1s289BzkfGswIM8qDfgsEhzJ/1aU=,tag:pF/LgWGztrTAPfSp+nS0Jg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
