ansible_become_pass: ENC[AES256_GCM,data:5FJ40AZdJbE3,iv:Z+pBpMs0YhjAYqCTJ5ZAzX/I153guqJJFmeT9LlfWsY=,tag:D4nkLi9X3KWC4BWzI7w+UQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bW1YV1IwWkhXNGYyb3lU
            d2hhR2ltMEtESjNYUnJlTUpYWW9aekt5UVZnCkNoU0hjVDcrRmM5THB5c3RmanJT
            U2dVaktxZW9QS2YySmY2VFNGVG1wNVkKLS0tIEpFdDdNMjRhUFRIWVNEOE14YXZx
            NU9vSHZnYmxyUWs4TGN5T1pXU0tvdUUK//InYtpNwo1hf44WTJRGTZa0HcippYKl
            8KC/gq0i3Obm8AlMsP8TLC0RLhZ28OnP/5L0YjqIvWtolVBjtNa4vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T17:45:05Z"
    mac: ENC[AES256_GCM,data:Ao6YWoZ7APKhSqA1NrNfNqITw9HuHOqej9k3te6qfOaFAjCISyYekZh8gqX20+szB9SDnpRQDHOfCZsw54kpJEv9Ie1hkxOkUPd+wMIt1AvYr1ATWpgjfF2DDjKLoP30RkVJM/Jlw5uvnxnt8Ijzhn+XJn6mA3gHreo0ZebJhJI=,iv:TIJHVBfx4+D7rjg3Ub2IyamQeKTswuSV4F1zjSGzhiE=,tag:cuuYpqiqJmQJckwZFAVOVw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
