apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reminderbot-clear
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: 0 9 1 3,6,9,12 *
          ttlSecondsAfterFinished: 86400
        containers:
          main:
            image:
              repository: ghcr.io/megashinysnivy/reminderbot
              tag: latest@sha256:46d9714f52527caae348f8ed668b3a0efbed6a8568059dd44d04306cd35c0025
            envFrom:
              - secretRef:
                  name: bot-token
              - secretRef:
                  name: channel-id
              - secretRef:
                  name: message-clear
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: false
    restartPolicy: OnFailure
