---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coder
resources:
  - ./clustersecret.sops.yaml
  - ./cluster.yaml
  - ./scheduledbackup.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cloudnative-pg-cluster
      app.kubernetes.io/instance: cloudnative-pg-cluster
