apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:WKCXMc1tB0fr+IL3,iv:xIqVeIoYBOahC1w0OFCMoxhjjOTdb2ar4eA22dfeFr0=,tag:yHpT2AMZCxT5Hdwkjas7SA==,type:str]
    admin-user: ENC[AES256_GCM,data:CK1Ldig=,iv:/o6C8vvMJxDS0HKokZCHe7ulkhD2W/LRnxQOjMVr9Co=,tag:oIWCdVEReMZG948UmCcS5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdTE1aVdIMkdkeG0xb2Rj
            NTZKamlHN0Q1emUxK0VMK0F4L3l0QmdxL0VJCjdmLy9KYjFxY2ZkMHJ2Y3hmYm1i
            dy9PVjFwV1M4L2U0SnZFMnFrV2NxWEUKLS0tIFRkNFl2UjJGL2JvTGl5TkJ1OU9p
            NTBXTUQ3UEVvYkp2TlRTOUd3MkpaNGMKy17x3qlz9+WO+iYrQabD+bSe+41aaObo
            1cD68aLY3OZ3T3Tsq4/YLQJBYtxSPf3nZrfGNe9x95KUSy7XZeXZfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T17:46:09Z"
    mac: ENC[AES256_GCM,data:qI4HZVuZZcLaqrgMdthMk5Mpd+vKkMIR3r8ikdvxHcvIW5JZGe8qjZQ+gBNcEDQ+NzNSNo87QIh2JVesDrqcaMglwWyEit+e+ZpMhlomIAdnhQ5iH3tXWLuS2Qs0G/KoiqQPciibFoze0R57M827SASURE1FoBxRwpTOplc4XF0=,iv:AXA0rlFz3jsqvRUxz2ccw6FhLl42ypp1nn/oMD1Y0A0=,tag:o6PRms7YCfiTxhKLTh1I3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
