apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:w2KZf58SDUmiupVpd2Bgz7WFFrAsHRXK,iv:kulPOU56Q1o9MMJ9Q0fR2CsNhy25KOFp3r/9vqhiU2s=,tag:MjkcxLryizk300ZyqJ71Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQmtLS0dxSldKemNkVDRK
            WHgxdlVLM0NneUprQ21rOUxGcWVUS3ZvOVRnCjJoOEtncTdibnlOQlR2dHphNDgy
            cHphS3RRaW8xQzBsL3IvMmlUdWgvQTQKLS0tIHJZMU9VVmZBT0NyM2E5d25vTGRv
            MWs4cE12Nkszc3Q2c0RtMko2QUpCUVkKERc9bGMfT3WxCZABQCKQE7ho3vgdrq8w
            izn/TWXpzIpnt1J31RxIvXxLpIpVXCizPiSEE9OOZ8PbKYKRT28y5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T07:56:10Z"
    mac: ENC[AES256_GCM,data:6AdGPSxVz1f8T+jOCq68qv3rQD0fNATv7WpC/rNTPwYxCSSw02NPC9edCZXueRenHB20MLQn72Df5HANP3toIg5NWdRLkUCEqaotISJXlXrkbZG9AlXFJCjn3Vjtk4g88gH7kghxyBjqJPl11VIigwXNx1CDY/SU+5tTILwftyM=,iv:Xk6swGWtVrPBjakF8Z8E7579B/4uig96P/F8xorDCvA=,tag:4D4AVNMGUzE40UDqwwW3mQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
