apiVersion: v1
kind: Secret
metadata:
    name: immich-pg-secret
    namespace: immich-testing
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:vurfu78Z/pqOzCTlNJRXIQ==,iv:yq11ZnhBEJbLCYWjJAIBYk/tmD0XUA2CjLqhVnJynPM=,tag:VIimvp2Sj1hvV2DSigK76w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:HYk+wIbNrZBHlO46l7bMgU5qis8QLnDggV/LuaA2Cbw=,iv:cqEmzRoU239QSMq2YRKlzvswGcEj9HA37lemCgHbt2k=,tag:4OV+f/WEKG17ZCU2lENEdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocWZmTHJja2hyY0FlMFcr
            bVVCVmpic2JWMGpOdmk1bk1OS29SY0w0ZXhRClVBcGlydnBGcDgrU1hPWjhZR2hP
            akNYZ3NMcTZGdkx5bjhudmU4T3NVTjQKLS0tIHh3b2xFZnBQb05WcFI4Nk1tMW1F
            T3BjbDA1cm5TbWFGUnNRNVg4dlhuZjAKvkO9kB2z0vSG7sIoCqM/oaR9Trc9wHCc
            igDELrDyYH10cnPxhkWOD/uVQenuiw/A0mahdAXzml84QbJCSf7+Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T11:49:58Z"
    mac: ENC[AES256_GCM,data:s3lIGjSscGiY+xKzJXi9GGxHzuE4YfCbf3TZ/T74HA3VwQlXGKAuvq6cpv3IO+2CtBCvP+bNAVvlJxgygB4NQFE69ypWyXkeXsx4YOpCoMpoxfxE9qGujn3tNKUYKIOE1LT3I0f2BMvkGj3QZrm7Z4urkg0TAU1LVORMksHnZlI=,iv:tgpow1TYjYRQ9l3ptLpXynz6S4b4jenrIYurFsJ0HCw=,tag:0AmtAJc8pK7xb8Uj65iNVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
