apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reminderbot-general
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: 0 15 15 * *
          ttlSecondsAfterFinished: 86400
        containers:
          main:
            image:
              repository: ghcr.io/megashinysnivy/reminderbot
              tag: latest@sha256:0aaa4a97e23e6106b9a2d3d3c0497ecff40ae584775e65e642f743258a755ad5
            envFrom:
              - secretRef:
                  name: bot-token
              - secretRef:
                  name: channel-id
              - secretRef:
                  name: message
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: false
    restartPolicy: OnFailure
