---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-config
  namespace: games
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "romm-config-dst"
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-assets
  namespace: games
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "romm-assets-dst"
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-resources
  namespace: games
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "romm-resources-dst"
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: romm-redis-data
  namespace: games
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "romm-redis-data-dst"
  resources:
    requests:
      storage: 8Gi
