---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app coder
  namespace: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    coder:
      # You can specify any environment variables you'd like to pass to Coder
      # here. Coder consumes environment variables listed in
      # `coder server --help`, and these environment variables are also passed
      # to the workspace provisioner (so you can consume them in your Terraform
      # templates for auth keys etc.).
      #
      # Please keep in mind that you should not set `CODER_ADDRESS`,
      # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
      # they are already set by the Helm chart and will cause conflicts.v
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: postgres-coder-app
              key: uri
        # (Optional) For production deployments the access URL should be set.
        # If you're just trying Coder, access the dashboard via the service IP.
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN}"
      serviceAccount:
        enableDeployments: true
      service:
        type: ClusterIP
      ingress:
        enable: true
        className: internal
        host: coder.${SECRET_DOMAIN}
