---
# yaml-language-server: $schema=https://kubernetes-schemas.kokoro.wtf/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app coder
  namespace: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    coder:
      replicaCount: 1
      # You can specify any environment variables you'd like to pass to Coder
      # here. Coder consumes environment variables listed in
      # `coder server --help`, and these environment variables are also passed
      # to the workspace provisioner (so you can consume them in your Terraform
      # templates for auth keys etc.).
      #
      # Please keep in mind that you should not set `CODER_ADDRESS`,
      # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
      # they are already set by the Helm chart and will cause conflicts.vml;fbkvdx
      env:
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: postgres-coder-app
              key: uri
        # (Optional) For production deployments the access URL should be set.
        # If you're just trying Coder, access the dashboard via the service IP.
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN}"
        - name: CODER_OIDC_ISSUER_URL
          value: "https://authentik.${SECRET_DOMAIN}/application/o/coder/"
        - name: CODER_OIDC_SIGN_IN_TEXT
          value: "Sign in with Authentik"
        - name: CODER_OIDC_ICON_URL
          value: https://camo.githubusercontent.com/f068956b02827bfce3b652ac3cbbe563ca05294aa149f73d1049059624445b37/68747470733a2f2f676f61757468656e74696b2e696f2f696d672f69636f6e5f746f705f6272616e645f636f6c6f75722e737667
        - name: CODER_OIDC_SCOPES
          value: openid,profile,email,groups
        - name: CODER_OIDC_GROUP_FIELD
          value: groups
        - name: CODER_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OIDC_CLIENT_ID
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OIDC_CLIENT_SECRET
        - name: CODER_OIDC_ALLOWED_GROUPS
          valueFrom:
            secretKeyRef:
              name: coder-secret
              key: CODER_OIDC_ALLOWED_GROUPS
      serviceAccount:
        enableDeployments: true
      service:
        type: ClusterIP
      ingress:
        enable: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:file-code
        host: coder.${SECRET_DOMAIN}
