---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: security
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2024.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    global:
      image:
        repository: ghcr.io/goauthentik/server
        tag: 2024.6.0
        # -- optional container image digest
        pullPolicy: IfNotPresent
      env:
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: postgres-authentik-app
              key: username
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-authentik-app
              key: password
    server:
      name: server
      replicas: 1
      pdb:
        enabled: false
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: account-check
          nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        hosts:
          - &authentik-host "authentik.${SECRET_DOMAIN}"
        paths: ["/"]
        pathType: Prefix
        tls:
          - hosts:
              - *authentik-host
    serviceAccount:
      create: true
    authentik:
      log_level: info
      secret_key: ${AUTHENTIK_SECRET_KEY}
      email:
        host: smtp.mailgun.org
        port: 587
        username: ${AUTHENTIK_EMAIL_USERNAME}
        password: ${AUTHENTIK_EMAIL_PASSWORD}
        from: authentik.noreply@mail.${SECRET_DOMAIN}
      postgresql:
        host: "postgres-authentik-rw"
        name: "authentik"
    redis:
      enabled: true
