---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
provisioner: nfs
parameters:
  archiveOnDelete: "false"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  storageClassName: minio
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.30.12
    path: /mnt/THICCBOI1/K8s-NFS/minio
  mountOptions:
    - nfsvers=3
    - hard
    - noatime
    - rw
    - user
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: minio
  resources:
    requests:
      storage: 1Mi # Size does not matter
