apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repo-secret
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:SGRdOobhrO6tTYQhaWQCEIBSKw==,iv:ZSMuK1QKQBIBhjGr3EFewEFbF/Yopg1rovQZZh1u5qo=,tag:WPBhMI1jGOF6Ppo/OGxTgg==,type:comment]
    #ENC[AES256_GCM,data:ePSP0FZ2nUJYsb7pm/Ia0QdZzHMyEws267Arqsnr,iv:RehatcmQjpmwriQNGtZG+c6jlqi8hkJ3cGrDej98NB8=,tag:WVBPwH9dnpXNTNohdnPEtQ==,type:comment]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:LWMIH7jyz4dTCtn9W1EsdfSknRmAPhBStoscW/n1BHfKnsEeBlFb3jv5vVT+c4mmHvQ=,iv:SFEP0fre3PzHoGR2AWBfR944c2mxp34hKHQqNMYxt8A=,tag:0BUQs+c2WCUly/vJ8uLjDA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicis4dElwbkZYM29CTElS
            TVNRQ0YvWlY3WHlBc0FlU0JTbFJ0bWtjeDFjCmx2VmJ2ZmxocGJIR05kd080WlM1
            amZpSUxoMk14eDh3RE1LMDE2c25IdVkKLS0tIHppV0FuVUIyUkpXZWtibkdLdUlL
            aVdiVEhKcjFoa00rWEtzK3ZpL2pGUkUKFnFEpdAZZPXgF04266ZyqQqlcpHyJeZx
            OmYikgIIQoJ2KzehhNmSmHi5rsAbdyZsPKEsrDrx6f435gc6unxUXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-11T01:49:43Z"
    mac: ENC[AES256_GCM,data:4UsV7XvQSIp9QnTjK/D+wo+WKZhWNP94V6cuBuKvufu3QEcLyHAT73h4cdV++OInsO9RmSwNXhUOSEpLiqb4u63a48K7J8rbT50TJB0obRHmIJht1HnKbjdF9XsE2q4S2hdNECeVAOz72xlnA3Czm4tOkVnZ/S+61tV5zdmLmw8=,iv:dBuJtB3mCftwz2a5DPLQ2gDlKl9iilQTg+4FAF7b3U4=,tag:0iQ1cEUiKTJFZxfjVgG3Nw==,type:str]
    version: 3.13.1
