apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repo-secret
    namespace: kopiur
type: Opaque
stringData:
    #ENC[AES256_GCM,data:tiFgjn61wTJRCqlztw9fUNqO8w==,iv:6m/SNAcUl0OX3h5J9ZYkm7Pc53sUrtR6IbydGGmBypU=,tag:PZpTN0xj3EOG7xux10mHMw==,type:comment]
    #ENC[AES256_GCM,data:vEHlCKEybdsWBXT5BdDJLLaQlCZC6bUckpNCikC+,iv:cE32DaAWrlkSt/X0v1hFA4rrijDl1Fd/sL8GyTBjAmg=,tag:f5oVkNSUAMJtKs7UoPTHpg==,type:comment]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:JhkWE/B6ntC103ZCogsYLst3HmDMkXwp/L5Bl2PZRCUbYoSl9PPZUii1BOcN1zmE/x0=,iv:iNjgTxwmm4/GFSwPdQn9Bfc9ketmbA/4a6Xpxoljf/A=,tag:A42D/oi7PFzlh7lGscqUPQ==,type:str]
    #ENC[AES256_GCM,data:VZlit9z3SNkQujnnN6PyDyl6F+61iVT9RK6aK72FNQ2gkBp85n+XR4w=,iv:VK52lMUDYGmQsbgwtoFpFLzIkjYyQYFAtTntrHw2hyE=,tag:eXq3q3obSGvpZvOGxkBK+g==,type:comment]
    #ENC[AES256_GCM,data:AsrejS0cbQQ8iXr8fSwAzxcZoEG56fdknDeT7Q6PskwoCl6EBrb9AIo9i6aReSqrdE99XxtLZ1p8yI1xPWCcc+8sTC5Z5Q==,iv:QKCrsNm2nMZryjygoUq4ebtMQCxnfHwpq7iIh6pLXfY=,tag:a60SrbTUqL/a2vSywL5ajg==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pfKTyCK8S9TJ+C2n+h+hFw==,iv:fMyyi8cPbwVC718BX6CFH9tb/LY6mjWp5ImqlkQbWzo=,tag:t1Del4CE4jfwdIu91rBQ9Q==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wXYNOXV4SGxUHSKTHUO2wZbwQ1cn/oVACPVExe/DMTo=,iv:nJfzI+wqs/ZCIEFNjBIqCX7u1nysd1J6gXG7i11e4ps=,tag:22XPKPBoXIebp/aG6AfA2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YmNGTHZQam5qL242WElI
            UmJWajV4Rk5PZGZmSUJjVFVnMjFnN3V5MWhJClgyTXNqOGlqdDk1NmdNSTZEVmhK
            S3IrSzRtbVI2dWlSaG1IS0xTM0JneEkKLS0tIFF2bk4weU8ydkxDZ3U1UFc2V2th
            c0dJbS9qR25qeWtZT0cvN1pjaitQM2cK+fyUrdmjGXboOPKjOqqXy9hNBJQjnzx/
            EhJVc0hTy/6L6drVDAppG269+BXCEX5nSPbGvB4Djbd9PvPfAeWDvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T09:08:06Z"
    mac: ENC[AES256_GCM,data:z0eFunEI6ZgsBVPLGi3mgKGcWDEEB+F7rcTZ8f6PJrMCCQA6oe0j2PsxsUJe5yacwVI4usXyQk4cR2JUvdw+AR93J3o5i669oTx8PLBi2y4T5k+KNruB4fxaLREiOzgIUzZFKSQ1W1aSvX3d0ZnkiyTDyYPlP+YphXuMRbQbKrw=,iv:Z+45q/RKzrnkZpkCksmC9rB+Ztm0Eoxea+/TJ8K1afQ=,tag:baWZtvC56hwiPhHMDaWTlA==,type:str]
    version: 3.13.1
