---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/clusterrepository_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: backup-target
spec:
  allowedNamespaces:
    all: true
  backend:
    s3:
      auth:
        secretRef:
          name: kopiur-repo-secret
          namespace: kopiur
      bucket: backup-target
      endpoint: 10.0.30.12:9001
      region: us-east-1
      tls:
        disableTls: true
  encryption:
    passwordSecretRef:
      name: kopiur-repo-secret
      namespace: kopiur
      key: KOPIA_PASSWORD
  scheduleDefaults:
    timezone: America/New_York
