# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: redbot-test
  namespace: redbot-test
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000]
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: jank.ing/jjgadgets/redbot
              tag: 3.5.9@sha256:68ad646e53086eaf889c9e2ce9042cf7baeb8f54d29057da35befe6fc68181ca
            args: [
              "--debug"
            ]
            envFrom:
              - secretRef:
                  name: redbot-test-secret
            env:
              TZ: America/Chicago
              NAME: Pineapple
              PREFIX: pl.
              STORAGE_TYPE: JSON
              DATA_PATH: /data
              CONFIG_PATH: /config
    service:
      main:
        enabled: false
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: redbot-test-config
        retain: true
      data:
        enabled: true
        existingClaim: redbot-test-data
        retain: true
