apiVersion: v1
kind: Secret
metadata:
    name: redbot-test-secret
    namespace: redbot-test
type: Opaque
stringData:
    TOKEN: ENC[AES256_GCM,data:BeiPwS0W5MQE7SsOQ+yAAXprzranHKoSfaW5uYxe9Ih/IEEw/Jp5i7kw+o3yYLZ32iSgevzVWKB4ii/WMAZL/PePYKVNfsDo,iv:YdmUp47QOu297cy9xP+NxXUnpglGuXe34wsbVtbZF+A=,tag:yZxMK0kJTgF6q7oNr+X6tA==,type:str]
    OWNER: ENC[AES256_GCM,data:SRes+3MaDBtUCXDmVxzE+XfF,iv:5BQFtYHFYUH30lI+l8IdlH2mFYyRZFSJdv3SHnFqFKg=,tag:CZAxb3H0vrYTNU0WrvpRsw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZFFCalZZdG13cDVnVUZM
            d1VVODErODNhdjV3V0VmWlhHS2V2WElReXcwCkJWVjVINGFaeXVmS1hzeUd5WVdu
            cklWRXNKdnltUmNGcTR6UnBlRFlUTmsKLS0tIEJxQ0FNTHd5Y0VrMUkrcms2Q2xn
            ajhRYXpPNWxpUzVkNlJVL2JoWlg2MmcKyw8Sz+pShf5PavyZIPdswgUMr8ig7n6U
            rQck8vd/EqwOfhNnqS+c9O+NlNexUgQe9M7ovinlHqUCneZNXE6qpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-15T23:53:09Z"
    mac: ENC[AES256_GCM,data:ugbzyZIN+rTS24XXlJpMSLB0Ld1e+L+8Ee0i8xzpPBfJBSPqptivO+90FDUNMaR2lrUXmQb+i+3SLj4N922454m3J6UFW8IVWoM8K4ZFPeZNfj0gXyNw+MH8X8KBq1RUBIn31hP5dNVE2ePwbbFvA53K7NXWyFfgENanQZmjtuw=,iv:3MLfN6874+ppb9/eLslwjnKlu843fPbOZ0i3SYnMjSA=,tag:Vv7LpvMWNTJPdHdlcWMxsg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
