---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-test-config
  namespace: redbot-test
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "redbot-test-config-dst"
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redbot-test-data
  namespace: redbot-test
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "redbot-test-data-dst"
  resources:
    requests:
      storage: 8Gi
