---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kyoo-transcode
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  resources:
    requests:
      storage: 5Gi
