apiVersion: v1
kind: Secret
metadata:
    name: kyoo-pg-secret
    namespace: default
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:FGl3u/tNF5rFrvRcgSPETg==,iv:tZLMk3dsaNRvOf0XHEacKoSpHCJv8+k1t5/zU6930mw=,tag:fNllGjX1Y+P4eWOGO/ACVQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WdMYITRh/9G0ZTAfydGtX6EeFBFrGGUujlbjNIqmcyI=,iv:9omAj/KnD4lSiMXLDSutWzFw9dHHXksAvx7CqK3v4vU=,tag:9M81V+yW6t3Yyu2tmoQjLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSVQ3SnRlQmM3UFExK2hH
            a3VuejBuOGFIa0NybmIvSXlJWlFKNmh3cDNBCjBEdllwcmZVL0JBWGx6NlFzNmtK
            MEgwTHNVRFJScER5c05LbEkrUklvRlEKLS0tIEkrM1d0dzNQalpCWEU4aTI4aDNP
            TzN0YlhIZGh1eG8wSVlFUWJmaVE5YmcKuO4hlBsnz1MndjIFadf9CoJq89BUlIYG
            4daKd9tYZ8rFOsTq2an0uTf2FmcpUmpCES7OGGDqZArQqCnXsoUFdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T11:23:13Z"
    mac: ENC[AES256_GCM,data:ByQugkjhb63ygZy0sfoC/9np/+oL5Mp9EIBMqyfqoQUXmB4VMAajUST2QPZeBtom4kpbbip9D9orQtSbp1lLTTl+MZOTZ0PELO9oJ2jebdmWNsZEX4isP1I0HfVpm4j2MzgDOK6xPp/dLLxK7U1rRgy2ipm7xNFvzDk+dkvKwZI=,iv:o61gOVmyQgcBaXwQjnbEUJGwS8odW772Ez0F12I5TRA=,tag:Kv6qTJ4lP++cpFviqhb4+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
