---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: thelounge
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: thelounge/thelounge
      tag: 4.4.1
    service:
      main:
        ports:
          http:
            port: &thelounge-port 9000
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:send-circle
        hosts:
          - host: &thelounge-host "thelounge.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *thelounge-port
        tls:
          - hosts:
              - *thelounge-host
    env:
      TZ: "America/Chicago"
      THELOUNGE_HOME: "/config"
    persistence:
      config:
        enabled: true
        existingClaim: thelounge-config
        retain: true
    resources:
      requests:
        cpu: 25m
        memory: 250Mi
      limits:
        memory: 500Mi
