---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: "thelounge-config-dst"
  resources:
    requests:
      storage: 8Gi
