apiVersion: v1
kind: Secret
metadata:
    name: restic-config-thelounge
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:GrhwrbxnXAFLIK8+0IRsCBdScA==,iv:srCjB9PLneRXgJLvy9bJfw5lFdks+hOX9f58z3X4FwU=,tag:XrSXDUCncTjNELDclmWccA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:h7+k1fGMHvAmsrRhglqzBGyQyQ67z/M8L8ZCfiZI4WF09KbEPzwnf2PwCC6YIxD/oQ8KMds4mf9ghCqReb0=,iv:hJTDjwBlUi63+TTutc5c+cGZBPrahXRj5H3ccHDbpeY=,tag:BUl8EhwHHBCH4hGLJP8DMA==,type:str]
    #ENC[AES256_GCM,data:kfHYR3IONFo4KKgtNiVEb+NKxXA4EZEUda46W0zF,iv:2ERbV5DKoWKBQcFwAaAGzUPDIUuZzqLoV7e93UQ2lCQ=,tag:PAvLShSml2kQKKOufho3Fw==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:S1f1K3VvfXQcISuz615auc9YWbnZmXdf3Z7le03PzXOLOfbGNnqTENH9bC4oCWooVFw=,iv:cOXPXtlRlAO/dDeMO2eZC/5M/9ITX8yh0KZhJ6N1TKw=,tag:7RFsdV40TBLK33p91xoYNw==,type:str]
    #ENC[AES256_GCM,data:WeAFrLM+jsPb9XVaqx1crPR4USpr99rFTvC2MSsLOg3Dlh9Mwv2Wj7U=,iv:c3QPMIOqYOlWIMMcXkrG0J8xdP4k2rNqwFogX5hKM5s=,tag:hMQnUDAVZ19KB8Va6jRzIA==,type:comment]
    #ENC[AES256_GCM,data:4DDu0yBmhRiKwkXaIEKFjhqVVoGg538AKzlbVWhzJK4FbtyHQlxUf/HGyFJz1Gw454MjlvsqLS5/QRxnrk0AC80LzwLaIg==,iv:5Xp1mQN3OjnaahpBclmTyu+EbOozT4gOR35B1E5Zukc=,tag:/FFDj+1kJGXO830/0h+kWw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:ayMg43jYG+bauU0SWzAP3A==,iv:G+yPPrfvz7xqJChAwfBVBs78E/phVuaTPXrH0fCtf88=,tag:RNpqu7j9k7PNoOam1UE3/A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:CTrLo2iWOFrlxqEEt0ZVvbieUC+LTzFKgPsEtrEbD7U=,iv:Mdn8M/MO7KQLkdB5eSE0BuNM5aIPl2zPKU6dhRXBViA=,tag:MVqRwyno15Jf/1LdWfy8pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N2g1MVFGL1hTMXREYzhm
            QU4yekhWdjZGU2xxdS8vYU1KNGpFeGs3d3dJCis0RDlpbjdDaVpFdUVGY2toZHlW
            SEI2aGxrS1JzUXZ2VldWOTZHRWllS1UKLS0tIGxJK1Nkbm9RaGR5enczY0VnS2xo
            ekMyTEdjQ09vcWZ6YnB2K29wajJEMk0KZi+3d2Xkdd7dUGFA0d9OelP4WaQpSwkH
            d2Kr9nRvcY6iFbFyuYKo19dIvX5kun4lDkCHWNQn0Hv65ejvx5Z4YQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T16:39:31Z"
    mac: ENC[AES256_GCM,data:p5LQ733LYa5DiFGg838UnEPjBbt9sEt7tinWAyc1EhWfZZvuCWITManQNYU4xO4yqt6R2kRC+YgPYYZqVDyMiO0f3EnJHYzzmTHwrhPH86veyzn4r8wf3ACqgvWxy8gvCb40fb29h30o6KFyhLZnZhSAbxrPbhYqHdqGv0d5+ik=,iv:n/3HfR0d0LTn3j6mEyD8Zj/Qz3LXFYDi3FS3w0mY17U=,tag:H0Zw2F2FCBUrCJpyuByVag==,type:str]
    version: 3.13.1
