---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: thelounge
  namespace: default
spec:
  copyMethod: Direct
  identity:
    hostname: default
    username: thelounge
  mover:
    cache:
      capacity: 16Gi
      storageClassName: local-path
    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
  repository:
    kind: ClusterRepository
    name: backup-target
  retention:
    keepDaily: 7
    keepHourly: 24
    keepWeekly: 5
  sources:
  - pvc:
      name: thelounge-config
    sourcePathOverride: /data
  volumeSnapshotClassName: csi-ceph-blockpool
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: thelounge
  namespace: default
spec:
  policyRef:
    name: thelounge
  schedule:
    cron: 0 * * * *
