apiVersion: v1
kind: Secret
metadata:
    name: restic-config-radarr
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rF2dQriz1IHwVKLrRd0Clt81JQ==,iv:LcaZCunPPBvQhANkuukoXehSGekHrJiu/scDq5xRcPI=,tag:OFb8dB3OG/gOHh2KmKZuMA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:31/eTQBZQi5MNa4RKCDSFrXDqwl124CFtxwFU6u7rxZIXIySeupcfd+XzYgeAqjXtlAghrU=,iv:QLD4IXs4rYD6S8BmmFah96mReA7/Z2GPX7q9edGtPLw=,tag:BlSNOEnR+nFfoA7vlcCVzQ==,type:str]
    #ENC[AES256_GCM,data:R+j14WZMufffHSsh710TBKEz2naReMcW/OHuRf2b,iv:cEdFHWvIUf/92xi2OswULdJXv+gMpxOdfvHoQnuHveY=,tag:euUWvpB88T1pnW685Wem0w==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:7WkD4Zoarp0+bUecO5qXWaUOCcUKnDV9h6F8RBpZFAPKD2GgHWFwQiqhq3J9hRELnHk=,iv:RM88h6XK+UYAhbzf0NYBVosZ3futgK+L68+O8ps+6Os=,tag:aGE9VqmkzTAzXJerI64tpw==,type:str]
    #ENC[AES256_GCM,data:FCBjKxNZirPOOJK0sGoop54dM+8lojwQG4pQQTvx7nxrplhpYG1UEX4=,iv:cp5jcerfjco9q82VWxNZmsmSH7641B3ig+XWQ3VbEy8=,tag:X4YvzbBtly7YANoIF/8WwA==,type:comment]
    #ENC[AES256_GCM,data:3ja4sF4d52PdE/+gYksu0BriiibfdhXqxG2wf0PjtvLKvJvGP6/ttrpWTTUKSdyHGi/dp6mznMnTAu6eTTKPlcLs4LTFLw==,iv:Z/6Wwp0I/pD7vwjCpXMXEbELk1upS77HrG1f7XmYHxU=,tag:PTj4Z6vbUK6E5gTwP1Omrw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:g62SbWQmFaFl5ZTZ050cSw==,iv:rge/+QU9EtCgG7Fvkv2LHPJWlXq+SQgvH/cmKklOIPM=,tag:WBmBELuwg4w0dQCO24Siig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3YutIc3MRGhleP9VOsa+sGg09pzT9lW/lT9oDIjcBzQ=,iv:5TBdz4iRclXF+kYg8WU7eU8TQXmV7Evfj+8d90J4Q/o=,tag:MV1AiVH844z0FQR/aTdhgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ3Z6OWR1ZFV0dlpSMVhJ
            WWVGUm1LU3o0UFQ1ZDV0dTNGNjJIaGZJbGdJCkszdU1ZM0laTFY5aG9OUi8yTU1t
            SW1KNnpNYmRWcUdXYWNQMFFFcW45WjQKLS0tIExwMXI1c2g3WFNGQ2RQdVQ5bGUw
            TUorU29YWU9CVEhINkhnMFF4MkI0MkEKBe0HQ0qLt4In5VzZguHwen7u740w6C7w
            sTtWm+e6WkSt2Q+C/OKxPPdj9QbEBXeFQo+0RFy2h0UHw5CM5N2yeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T13:34:03Z"
    mac: ENC[AES256_GCM,data:WRfrH//U5t9HdmkxVsRAmZ6P1cw3xzmu6qUecJIpQgXo5r0wPTVrpNkRwoMtRAexGvIblnDtZCx5H5+5blkA4FYXiMaqvs75xLbc8XKBEoIqPwxMx9Uq72PhVfdfxNHkumODQNfbXi2MkuKypjtVnqAg5Dqiy0oBFI0u9CUVRe0=,iv:nfHWpyhmFCPgLPL7SKz3cTAceg6JGVxreEqXGYAWAqY=,tag:NgOmZiVcbNgSHwrhNegLlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
