apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:SoDowbp67/BV7ft4,iv:gm4eDItABajcvYRgTYXTd62ooAp2VBDGk+eAL/EtexI=,tag:1SSB3uGU8sjjgQrRIgq+pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VVJwYU00bktsZ0lWZEs2
            OC9MZmN4YlEzeTJ2Tk5jdEczbTQzQmxIamlVCkFzUzVtTUVhaGthdm1rMTJNY0hx
            d3VSRE1laXNQZkpMRUJ2Wnl3Zlp4eXMKLS0tIEp4TXF1U0FubjNDSWlSazhZVEc0
            VnBqZlp0K0ZIM3dKSEZXRVBmMnpOb0kKYX6fN6dfwvnxbNghhwQ+NAbhcK3A8LOc
            wEQIEkmKb2dzSQsJ6nFCdRubuHdgMwEW7+umBH2BCUqX4PE8fFpLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T19:13:30Z"
    mac: ENC[AES256_GCM,data:cUVZ7vSm4Jq5zyffSMCtGahOxnaIyJ460qk3IQv8GK7UOmgwgMz+THht1jR4w9HLDt/rmjzUpAra81KCfwJeB99p7SQB8P6iEUcTATbywOvGw1ecDHNMhGO4I3XALy/wQAr2pY92g1Kwq1rY3NvfOYYIVY5KjwF7xaoQ39eC16A=,iv:ynFuLBYGVUwVNne04nE6c2xOiKDNQ7f2YFxF017l7q0=,tag:nVYMmD4T2rRhJ58o+Zsjfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
