apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:SoDowbp67/BV7ft4,iv:gm4eDItABajcvYRgTYXTd62ooAp2VBDGk+eAL/EtexI=,tag:1SSB3uGU8sjjgQrRIgq+pQ==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:VK7fluoMp0ZBrsU6ZKM+MBd94cn800hVozt4RfcN0PwD+DamLE9tjnuvXk6WNxjT+yc=,iv:PshliO2hHL5g/K+HNB7usdaipENMztVeutglXeG4OWE=,tag:cdrgpWOj7O9llMAEXR0ynw==,type:str]
    AUTHENTIK_EMAIL_USERNAME: ENC[AES256_GCM,data:kO4VI7PDLWS6g3xf6OK5YrczSSYgVCyKFvl/GrjYkEPNWA==,iv:dozhCxhbsKHyKca1QyMWbSgXEnx5KoEIucnJ5fcnw5c=,tag:pABjwd9aTCcjGQld+FzgxA==,type:str]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:4Y6osTUCFnndRZ8OC2Q4NNv3kOERR8KA7gUNIDiRSrO7ewJTtb9MPimxecl3QucMxRs=,iv:L+1wsmRMrBJ7eOS2q6NmOHpLem8+99FwmnaReXHx4OY=,tag:DsS9aNJl2NCzLsYpSCa1SA==,type:str]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:6qECLOvb41AXOEb40nU+G1JxYY7MB7FVzK2ohjsBm0Cv0y9QZer9rDSt1EXGQ96VFWo=,iv:wVLPZgFZ6c0/+myfdpNQQeT/RjAExQCz1OnKUO6f5eg=,tag:Jr91ZttFPy+nakCpIwC0wQ==,type:str]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:YhS/WBfOcNoMJVkbR0TwT/QD54MCR+jEuHCHFV8D/z61tW8c850u,iv:3RPddU4qi3P5+Tz7cb1hctVLiyILvKMQKek/mZqT30o=,tag:Yc7zWKDPrn2E/BIiGjlQ4Q==,type:str]
    AUTHENTIK_POSTGRESQL_DATABASE: ENC[AES256_GCM,data:AmVUd1St0iEg,iv:Sz6JSSBqP3Pr+DBa8aDR1SENvAxEftN0fKv2pCRw38A=,tag:QOA1q71J6uVdUMNVCSOkbQ==,type:str]
    AUTHENTIK_POSTGRESQL_USERNAME: ENC[AES256_GCM,data:OAZ5pe5N0Cwu,iv:e1K94pisIvmGU7tkI5geCBcHQw6PQWBV3SEZlMFjdSE=,tag:tRBLFe02HknG0xuXCf8O6w==,type:str]
    CROWDSEC_INGRESS_API_KEY: ENC[AES256_GCM,data:1pRPqpUhcKKwntSeeXyU9PtonUmqvd8Ajw==,iv:WJSY7CBIgNr5Dy3GPiI+EZgO0J3gPdvME3AmpBjyfPA=,tag:iBIH3OwK8Tir3HCkrvMJ4w==,type:str]
    INGRESS_API_KEY: ENC[AES256_GCM,data:K/+L7/M92KmiMZD0Ut4WQYqgN9twmw==,iv:2ccIF8T/6vVrRYv+JvSIU81bKbGMhHEVOSH4/4qTfVI=,tag:LN/WuFAfaZ7eMTFemjN89Q==,type:str]
    CROWDSEC_WEBHOOK: ENC[AES256_GCM,data:HfCiLIv9MqRawF9eoDG3NqiPG07FN7toAP+rtMe6ZSz8GJ42ofV2fczbN4no2WeMCHHmwwtDkYfJT9L84lw7eC3QXq4ligJF7su2rjn8Gz36dE6dyvK6fAPjFW/RPg3jpysIcRNC0Xzhkakj/0oVWw0QpliQBQAw3GPMSyRY/w==,iv:4G5l+IHSg/2Rqld84I0CPz62KScKBYlpnqarut2YS3I=,tag:0ZbgK56M6RdU2bAzYArdhg==,type:str]
    ALERTMAN_DISCORD_WEBHOOK: ENC[AES256_GCM,data:h4PGuyR7K2X/bSRN7e/3gAmO4PjbA5KeqS1EtJv8s+f7buO1c+ePMdlxzEW1wmQSji9PTDDcYoXe8BfBJhpp+yB7bHkrSgIn0bdr4o+MmTwoXswj24tBTbtkD6ZZ0hpTG/61e9hYHQAQ7Cj1AMUjks4Hdgi1rbKCqQ==,iv:U5EqbiVuBJ0Mwv4UspnIfKQx8f5EUEA3Aawo96KXKL4=,tag:LGn6JU6D0+i+FwMHp+MBqA==,type:str]
    RABBITMQ_PASSWORD: ENC[AES256_GCM,data:TjuHQQdOPH8BG1f6WUlP,iv:I5IRWjudreezYO7IztuHWBDUxIOYfSypSDh5syiBqto=,tag:4iSkp6UXKEi8gOiEWOkxbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VVJwYU00bktsZ0lWZEs2
            OC9MZmN4YlEzeTJ2Tk5jdEczbTQzQmxIamlVCkFzUzVtTUVhaGthdm1rMTJNY0hx
            d3VSRE1laXNQZkpMRUJ2Wnl3Zlp4eXMKLS0tIEp4TXF1U0FubjNDSWlSazhZVEc0
            VnBqZlp0K0ZIM3dKSEZXRVBmMnpOb0kKYX6fN6dfwvnxbNghhwQ+NAbhcK3A8LOc
            wEQIEkmKb2dzSQsJ6nFCdRubuHdgMwEW7+umBH2BCUqX4PE8fFpLtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-13T03:52:24Z"
    mac: ENC[AES256_GCM,data:340VpWBzAQ+X4BcCz3+8AlM1f+cvjpvwpXVuUo3DWOAQaFBQLHq/ANbu7EKZ2tJSZo+y4LZR0JxdgiWtoFn2Q495EUIxYV+6nF9tJs8br4wkjuOKluD25OhVO7RvViX1dIJhhMH17eSdr1CXRuFMZkSviqF7Ri94OPcExn9k1YU=,iv:VfCWqiksAvEgfTOSohpAX9m3jv5+y0+LQr3zIoIeYfo=,tag:hjMCYkIAT2WWBVidmAhDBw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
