---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: screaming
spec:
  interval: 5m
  install:
    timeout: 15m
    remediation:
      retries: 5
  upgrade:
    timeout: 15m
    remediation:
      retries: 5
      remediateLastFailure: true
    cleanupOnFail: true
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.9.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    loki:
      enabled: true
      image:
        tag: 2.9.3
      isDefault: false
      persistence:
        enabled: true
        existingClaim: pvc-loki-stack
      config:
      #   ## important: limit
      #   limits_config:
      #     split_queries_by_interval: 0
      #   table_manager:
      #     retention_deletes_enabled: true
      #     retention_period: 2d
      # query_scheduler:
      #   max_outstanding_requests_per_tenant: 10000
      serviceMonitor:
        enabled: true
    promtail:
      enabled: true
      serviceMonitor:
        enabled: true
    grafana:
      enabled: false
    prometheus:
      enabled: false
# aaaaaaaa
