---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: sonarr
  namespace: default
spec:
  copyMethod: Snapshot
  mover:
    cache:
      capacity: 8Gi
      storageClassName: local-path
    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
  repository:
    kind: ClusterRepository
    name: backup-target
  retention:
    keepDaily: 7
    keepHourly: 24
    keepWeekly: 5
  sources:
  - pvc:
      name: sonarr-config
  volumeSnapshotClassName: csi-ceph-blockpool
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: sonarr
  namespace: default
spec:
  policyRef:
    name: sonarr
  schedule:
    cron: 0 * * * *
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: sonarr
  namespace: default
spec:
  source:
    fromPolicy:
      name: sonarr
      namespace: default
      offset: 0
  target:
    populator: {}
