apiVersion: v1
kind: Secret
metadata:
    name: ocis-secret
    namespace: ocis
type: Opaque
stringData:
    OCIS_JWT_SECRET: ENC[AES256_GCM,data:zrKRyg415qkHQ1AYToKEbxv0O4TIO2yJXotmtErfr7g=,iv:5p3P9U8BoPIbUadZFwiwR8djdoV1gOW3S9siOkM2Xjo=,tag:Liqg35wajcZDHqreqYvI2Q==,type:str]
    NOTIFICATIONS_SMTP_HOST: ENC[AES256_GCM,data:gppHWFdlPVQW9Vn+AsmmeA==,iv:SJte9ybltIyKItjnBXQwWdfRUuiXW46xNh2kiTDBo7Q=,tag:cIX9Crtu2akmIzKyhT9uuA==,type:str]
    NOTIFICATIONS_SMTP_PORT: ENC[AES256_GCM,data:KvUg,iv:cFtvyw5BZuoFQi6U68FuLEVUNtBtmI9TM6Vq5vllX/o=,tag:E5d1CA4saXB8IXFk619Jbw==,type:str]
    NOTIFICATIONS_SMTP_SENDER: ENC[AES256_GCM,data:rKbnEq/GX+hzoJsgGy+meLVKeQbHwKs7PeyM9Bxy+tMAfNwK,iv:Zpy2fSX5R73CNbk8z3qXG8L4r11hGJSbyzT3XsAFETY=,tag:Rf5XiZ1z8DpzHaeBySg43w==,type:str]
    OCIS_OIDC_ISSUER: ENC[AES256_GCM,data:FJug0rYAaKbxXRh8rKo8aSAiRgxoXI2HZ9tH7Ur7HdNp5VMpfcF9Kqt07uwIS6i7vqOhEnJ8RTQ=,iv:Pb0u9OH5CP/Wo10Lv90IdS3sjZEvq6w5VM58LuneFNU=,tag:KODIPi3K74cw/9+v8wT+2Q==,type:str]
    WEB_OIDC_CLIENT_ID: ENC[AES256_GCM,data:cs2JR85oviHVEJwXSfVThbItg/3bL81z3t/8qPQA43+X3rsTtv8pKg==,iv:zd5jVjDsSKFNFMPFXv5lJs3pNq9jfBgN9xYcYDjiAbE=,tag:kysF+gK4cYDp5R0+3sXeLQ==,type:str]
    WEB_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jI1MVCjX0ntqNyvPR95wCh+YhNxNPbuilK+0t5Vb/iaA7XevMnI0I85QLm04Ldr2hhwNlik7Uulg62Kv5xN/eO5TIXJTC5gXusEox7ZlfTNSvYzjpi3VfpRDgRGB4gW104kKjkIiTliymITlG3c5bx1sqCKwK0pRx4ZiKWKygLI=,iv:f9bpCnHiThOvQ3siFrI0eZCzS2HccCqPqTki66WXvMc=,tag:VoEEnXf2OTpe195x0qStTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcWd3WitkemRtT2I4Zm05
            bW5nRlM2SlBYUWRzUGsyVGRjUmVBRDRENWhZCnAxOXF0Y1I2V0wxVWorVW45RjlI
            RlBYYTMzeERFSGhzUWV1ZFhpM3djeTQKLS0tIGdBYXlRMVJ5V2p2TlZQSU5kU1Jj
            d25TZUdGanpvRUtsNlF6ZmIva0FBR0kK4aOQTnXmJLo75vPAoMcz/TE27ISG+aAE
            MaQLQe5YSBWtL5i+20oPJbiPlvtbXGt0/9xwyNSccYoknWDxOazPXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T10:57:51Z"
    mac: ENC[AES256_GCM,data:jfb7AEjCvP1kt6UkEDXhvT4l8taR3IbLEV/HUT8DzKdjOpYLprJyqtNHfbQiSajI6TYenEJBbAhlwJnJTG+Wv2AJHk6xy6ACO7ulZ7SmnbyDPdIA5ouL+4EH7n/BhnYqceRf2A/PqiIcC+1v/02s9qjSuqtxt14VXd0hNwZq1c0=,iv:kXoQcnb26goxYDXGhLkLPj1Q71uEwaJZnOjl7jFO/t8=,tag:lGFO0TwXu3K/I4uABuSArA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
