apiVersion: v1
kind: Secret
metadata:
    name: restic-config-jellyseerr
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uasptCvVqceC66jpoix8CwAgLg==,iv:2P7/ZM6wcNPY8Ca4JzFcNnO1xjp5qID03HdhC8TRXH8=,tag:OVc61cOqzJs2XWqZ70KPRA==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:+EfDlx0AEZFc2Le4aAKYfPul35pDZA7v5PZTIf8oWAt1pPtFaOjHr2Op629gJA7tU4Kpxj/a8rZJCvjU5zni,iv:dR0DiYbfheyydpYrr3Zv0NnkIopSgN1jPKEj5A9H9K4=,tag:Tnn/DeQhF/RIKmqfO7t7Og==,type:str]
    #ENC[AES256_GCM,data:CsRLN4GZN3FzqDrK2wMj/7D+6skgXeqRmWMcJ0pU,iv:Xsd706uWWHJWRyp7B2Ce0r0eMZyh3khnPPNiK9PdLTo=,tag:df0YaKkVQfXTiCXPChtLiA==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:E4nWggnXGKiKxmYB8jK3IJwdKKgDUAoMw2ySOvCpA4V0tksXfaHNxmBzG+22gt12hFs=,iv:wuVHZDdEp/gov65WOTpuS1QyK19U6BfIXI6bnM6OyCs=,tag:D0yWPPugZP7s4hv0QFas5w==,type:str]
    #ENC[AES256_GCM,data:X24OuOfAwTfVLbt6ymPPu1L2og1plmnrLX7qAZBBHrZPKJifVsiN2L8=,iv:WY5Xk+s7/eS3Zo9b0tssj9OWjUwFq/sy7XEM2RWXX2g=,tag:Q23dJOd25bw+Xhs1LLrAjA==,type:comment]
    #ENC[AES256_GCM,data:W0rHS6M00UPJ7z/F2Ea5RwUBWHnJam0crUxJ1ePBvLb1fwRHcVeMysTRlZ5pjQvVHW8ZOrpxjJutD57COlhYpobhsDPppA==,iv:/gA3Wp+zRhJo9uy8lz5LhI9uL+bgkEq8d/KoPK6nV3c=,tag:Mt7KvgWUHdu/LcEqG1QRjw==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:xXnsEoHXc2iFZf9g+lvPFg==,iv:SM/6Not2IT2vQJQaARA/qx80UJeJZTwLCKwbJ7ivUzE=,tag:OP+MJem3P8cs4C6WtnKsCQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:j4NqIWI8pAPHOMdkKRPkG88UV+wbXbEOOz4rVr8b5II=,iv:HMUQOoKXuyUc+h1Z9JoVgKDCwt+4zNIMVQP3WCW4N4Q=,tag:eaPzWKTpWTBf8OJUE2ov+A==,type:str]
sops:
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcGVuWENhUHlzQWNMbkxE
            dE5YZms3a09VK2dMSklONWZqOUNOdG5RT0JVCmx5b0hLRTlKc0IyV0pDQWp0WVkx
            SFJsRFpQM0JrdEdIUXZTUUFzcHhqVnMKLS0tIDErZUR5NkFlaTJiczdFR01kSkda
            eVd1SlBlM0E0RHNxZWZ1YlU4aXJaSG8KqWMI1JvY9Wzdp481wTYEDX12O3ICvqOU
            dQBEdPH283viuVxXatVDvXTY7v+/0KbJUiB4gscG8YxRyOuG8DxZxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T15:13:26Z"
    mac: ENC[AES256_GCM,data:50dwObwaXyrPayCyUWu40BWdWPWulf9hLtyBvC2NsvuqG1gPVtQjsGlUeJT1M9ldwrB+qfd/VKqGtbh0EC7IwUc3fgRy1Ny/yykZDTQbDZpm6yA4IyY9zFyiQivs8gRSlfc3SL/GSGuVdEUbY4gpjjfDDaDnM6NhscRAx+HJlXA=,iv:fRWIx0NECi/JIjTEv5w33SCRaMopg3i/v5mDRj6XySk=,tag:Yx33jVOcaa5LmduEivsioA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
