apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:gfjkMxdNiTaH9oE7CrymMLnavsO/wDbHST3TfNqDufD9J3cr,iv:76I/p+oaBZqbp/Arg56Cu79PjojBK2cYLMH4bzEnV/A=,tag:YJepZQz2wWyfyP4IYpujPA==,type:str]
    credentials.json: ENC[AES256_GCM,data:cMB1rTIFdf43vjRKLzVax/7wYw7nWBeohMrHdyxtOQ846H8wa6at0afN/qhozNU8DJ9ISLoEsUkAwJ9L7oNoJC+2RuF8hO9jAodzWmb6PLN4se+nKxv5h4GuViUsM6rOV1yXl5iGLgldlylrNwNdDJw+zBmECTUS42mJLPNAVvFc96dOYH2U0MjiWacmxlkXaHb4JpFqJzMjnuRWOd+WUwXFNyAS7Qm2c0zEw/RHgQ==,iv:IUfyoUlOxN9yRdDEJw+zXvSfoS2Iq6V38rwZ78cJna8=,tag:FhvXeoVtDlMoOnCfJS9frQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBza3gwbGVBU0hRR1hBY0N3
            Tnhhc3RMeDRBOGtRUlhkZkljNHdwMEQxL1NvClVHUHNOaGpSOS9uckdLbjc0dXZN
            VlNla3NOa3prOXpMSWdMVmk5UTFSK0kKLS0tIHJaMWt6b09mdjRJY3VQMm8xTzlX
            UlZSemZsemJiYk9uTVRmOGpHYnQxY3MKwDM+KWXg+IireaXVf2JeBCU9gpOXlOdf
            TPzmXJrPUqdqm9cCvWm2KGYT2q6QrzzG5O842abvjh0Cy8kzlzQwrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T17:46:04Z"
    mac: ENC[AES256_GCM,data:sd3P9f4Yc5GRUVsKvCZb4oUl/8D6ydJODA2+TORcEEQR1Owr4WsAT/oFAoO5nPSkg4OcjWD0XJHgTG78LqbSsEmLJtyagHPnYs6l/XHYwveQLFOkdTuCVuovd+bjGzBhUP05kVrQegYknDCaeKJFlJFDzUmqYsoKXTA8k9BQCks=,iv:xjHWnmxat6zGIENKqQS9tXZoEyuR56mbv+rzJiupnXI=,tag:tFPytp0I75vc2FDwAAF0dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
