# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: satisfactory
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - k8s-worker-3
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: ghcr.io/wolveix/satisfactory-server
              tag: dev@sha256:657df25002d6e6ff258aeae08defb8d73ce7c09c7b07fad57f865910a732481b
            envFrom:
              - secretRef:
                  name: admin-secret
            env:
              TZ: America/Chicago
              MAXPLAYERS: 8

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.10.151
        ports:
          http:
            port: 7777
            protocol: UDP
          sub:
            port: 7777
            protocol: TCP
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: satisfactory-data
        retain: true
        globalMounts:
          - path: /config
