apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr-anime
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      # -- image repository
      repository: ghcr.io/onedr0p/sonarr-develop
      # @default -- chart.appVersion
      tag: 4.0.1.953@sha256:d26b5432cd1b275ad33cb4614423b8002f6aabad2efd5c098b044e6ebea550d4
      # -- image pull policy
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
      SONARR__INSTANCE_NAME: Sonarr-anime
    envFrom:
      - secretRef:
          name: sonarr-secret
    service:
      main:
        enabled: true
        ports:
          http:
            port: &sonarr-port 8989
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &sonarr-host "sonarr-anime.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *sonarr-port
        tls:
          - hosts:
              - *sonarr-host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
                read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-anime-config
        retain: true
      anime:
        enabled: true
        mountPath: /media
        existingClaim: media
        retain: true
      downloads:
        enabled: true
        mountPath: /downloads-usenet
        existingClaim: sabnzbd-downloads
        retain: true
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [1000]
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
