apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr-anime
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000]
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
      # -- image repository
              repository: ghcr.io/onedr0p/sonarr-develop
      # @default -- chart.appVersion
              tag:
                4.0.8.2008@sha256:737662938d4373ec8b5d80ac37bb96c24637cb1871bc55c74c54ad66af43fafd
      # -- image pull policy
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: sonarr-secret
            env:
              TZ: America/Chicago
              SONARR__INSTANCE_NAME: Sonarr-anime
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2000Mi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /usr/bin/env
                      - bash
                      - -c
                      - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\>
                        && while read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo
                        $C; fi; done < /config/config.xml`
                    failureThreshold: 5
                    initialDelaySeconds: 60
                    periodSeconds: 10
                    successThreshold: 1
                    timeoutSeconds: 10
    service:
      main:
        enabled: true
        ports:
          http:
            port: &sonarr-port 8989
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &sonarr-host sonarr-anime.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *sonarr-host
        className: internal
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-anime-config
        retain: true
      anime:
        enabled: true
        existingClaim: media
        retain: true
        globalMounts:
          - path: /media
