apiVersion: v1
kind: Secret
metadata:
    name: vtt-secret
    namespace: vtt
type: Opaque
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:KV4KBmEedKGh7yLl4u8=,iv:dxfCKXcMTvs9YWERiQSMkM0qyhpnIza86PBP7FvRpew=,tag:4+hcC9kn6XqLvBK/bkn26A==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:GMtifg6+fXlWmxo=,iv:Pg7Zlx6k7Wl8F7VDFEbZbP57w/q9qdx4gVrDZoI9MaI=,tag:Y2wOfdyas1iwJCOx8M1bKg==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:qmWRpOveOz1Cf2MjyYytkA==,iv:WJ3vcD6Df18VSNfqUtQbFuTOTQ3cjpwSEQckKRSt7TM=,tag:165wkn4Yq6L2Y8d/IAm7HA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHQzaUNkWTNSd2I3dEZy
            VTBnNkM4eTZNNGhLSEFKSk41MWs3NlYvZGlnCnVQbFFKYU1ab1M2aXNJcW1YbXl3
            ZlRtUUptd2ZqQ011VTJlVFVWVFRlTFUKLS0tIG5hYiswaEVlakM2OVlGai9MTnRm
            dWJmV1ltcXVyVStsbHJnbmU5S2Rqb2MKdNT5raUCtDc8cLRDCXfwjnWu+8S3Joe5
            WvMuh/IDpowTuh6ucygTLL29O7aYgClc07WNpjLcZ0zzTQ2aprRqHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T00:45:06Z"
    mac: ENC[AES256_GCM,data:MHUZLMvzI23qzICB+tyMs1JxIq7JaFsCKvQ8fL6l54rjABzmB0cuNHPkbdCuI544G3QPaMkoqgzkBJcxrTSWGezFbffIlf9HdV8xwUDE1+NlmGuqJPQ/87lBXP6ajliJLX00Fk+Mq+nL+mTlmrdMcAHVxZ623MHL0AFOJNHOaUk=,iv:gK409uw2fdQB/3wbDXmh1MhUORDhN9qtlX2pVmXYDqE=,tag:caeKEpMk6OXmAaXxHDe6Vg==,type:str]
    version: 3.13.1
