apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vtt-config
  namespace: vtt-config
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  resources:
    requests:
      storage: 8Gi
