apiVersion: v1
kind: Secret
metadata:
    name: vtt-secret
    namespace: vtt
type: Opaque
stringData:
    FOUNDRY_USERNAME: ENC[AES256_GCM,data:KV4KBmEedKGh7yLl4u8=,iv:dxfCKXcMTvs9YWERiQSMkM0qyhpnIza86PBP7FvRpew=,tag:4+hcC9kn6XqLvBK/bkn26A==,type:str]
    FOUNDRY_PASSWORD: ENC[AES256_GCM,data:GMtifg6+fXlWmxo=,iv:Pg7Zlx6k7Wl8F7VDFEbZbP57w/q9qdx4gVrDZoI9MaI=,tag:Y2wOfdyas1iwJCOx8M1bKg==,type:str]
    FOUNDRY_ADMIN_KEY: ENC[AES256_GCM,data:rzrXzr5y9d3V7X1IsxDfIg==,iv:G43+JPXef5pV8U4xZBtnf9NQCxlnv8fuafOtngnWTtE=,tag:FVV7nR361i/m1+fin+BjJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eHQzaUNkWTNSd2I3dEZy
            VTBnNkM4eTZNNGhLSEFKSk41MWs3NlYvZGlnCnVQbFFKYU1ab1M2aXNJcW1YbXl3
            ZlRtUUptd2ZqQ011VTJlVFVWVFRlTFUKLS0tIG5hYiswaEVlakM2OVlGai9MTnRm
            dWJmV1ltcXVyVStsbHJnbmU5S2Rqb2MKdNT5raUCtDc8cLRDCXfwjnWu+8S3Joe5
            WvMuh/IDpowTuh6ucygTLL29O7aYgClc07WNpjLcZ0zzTQ2aprRqHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T01:45:48Z"
    mac: ENC[AES256_GCM,data:aDF3f002B5OKJk+EiPjSTZchCgdFSEfLW2gQZ0VVKUYGpeWiMnWGVTWt3Gzlsb0Hk21o180Q1q/6YreYp1SGlrj+OlEIoIAg6JjC6SR/OeOi+5fMcXq/4ZOzazWFUQyyfJeCgMkW7SExe7MRyR9h8nK0Wxl8+t+ahgFBjV4E5Qg=,iv:cDvPLzrUrtBs8nCiGGQg0WGDERMQhQnY2ssnCLqoDNQ=,tag:5MDzxI17Ibff7txBrvKULQ==,type:str]
    version: 3.13.1
