apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-password: ENC[AES256_GCM,data:TWyYd+eBe+/iEOny,iv:MRe0PLOm0y6R4fXSrJIWVFSKLvbeC1rfH23FpRRdkUY=,tag:B9VIodBivdPvLhKTkVYJ4Q==,type:str]
    admin-user: ENC[AES256_GCM,data:kIDlR9E=,iv:1KE6CA5abkpmWVIHuMXgLG7Fqs7o0nW8/jauBeVLLQk=,tag:g5Kdg2fLJNpW8016NSlREQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aHp4em9lOUUySFpRTWNn
            Y2pNdmN3Qk44d1pabW9wNkZFOGxQMEVhUlRVCitXUk9DWWdzME12cDN3Zis5SFNk
            SHN3bzZvaGRmY3JRQ2FXd1RUWnM0OUUKLS0tIDEyV0svZzJFNVVmZTNzakhDUVF5
            cjVOZnNLZmxlYUFhdE1vMHQ0aktlNFUKhU/tEyjz0ll8JoCJ8h4OEJAiBBG75hFa
            3edAikXq1sLPU/vokQgieM0xX+1doYTAveyxwUtX4xT3I5+1ORG33Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T19:13:34Z"
    mac: ENC[AES256_GCM,data:02T6WCpkgVfylSECTdQyJoXxUXWD2zn/pc4HRz0ziT8DFRh9XstCZ3ppplxECZs96XiEcZd6oMPDxSfF9BO/n0/5CB2m5ki04DT9TVZB4VilG9rgKNSxrMBVAp2w0YgEk+MH6CtdOSKvEHdWov+EE3DhWP/G0CKgUojWMGFRi+8=,iv:tp5PD04aUOZheFoGhQzQ6UJ51YztyWHZBOu7pKhcDP8=,tag:5cicsHl5rhI+s7ZAdvMeww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
