# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: komga
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          main:
            image:
              repository: ghcr.io/cbc02009/komga
              tag: 1.11.1@sha256:a6b3a0559aa422652926fd7c435aa82be1d4465ae36cf9a60b4bbae6c465931e
            env:
              TZ: America/Chicago
              KOMGA_CONFIGDIR: /config
              SERVER_PORT: &komga-port 8443
            resources:
              requests:
                cpu: 100m
                memory: 2000Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *komga-port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *komga-port
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:book
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host komga.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: external
    persistence:
      config:
        enabled: true
        existingClaim: komga-config
        retain: true
        globalMounts:
          - path: /config
      books:
        enabled: true
        existingClaim: media
        retain: true
        mountpath: /media
