---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: komga
  namespace: default
spec:
  copyMethod: Snapshot
  mover:
    cache:
      capacity: 32Gi
    podSecurityContext:
      fsGroup: 568
      runAsGroup: 568
      runAsUser: 568
  repository:
    kind: ClusterRepository
    name: backup-target
  retention:
    keepDaily: 10
  sources:
  - pvc:
      name: komga-config
  volumeSnapshotClassName: csi-ceph-blockpool
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: komga
  namespace: default
spec:
  policyRef:
    name: komga
  schedule:
    cron: 0 0 * * *
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: komga
  namespace: default
spec:
  source:
    fromPolicy:
      name: komga
      namespace: default
      offset: 0
  target:
    populator: {}
