apiVersion: v1
kind: Secret
metadata:
    name: restic-config-komga
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:x+Rc+Th3LDibIdeGBUrh17DKYQ==,iv:B/7u8fxAb0lfmbSS0vH3Pm/Ng6gaBwRjcCCGBXcaGnQ=,tag:iagiFUZyyhWpdo3zQ9hCJg==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:GqVVf0ZvZYQt0cw69KH+Z4Fw4yQks27Iu1ZXJYbNFbGLDJbZVaEGFrh4jIwwMWZB9g44Xw==,iv:HzhDj+iRo3wrg4QIoTsK10F7oizM3bF/Ea8VG/MxBy4=,tag:woyBK9duA9Q0qIPdNu1dHA==,type:str]
    #ENC[AES256_GCM,data:bBmQump0rYW27Hxc4w2OXc23gH5Dj5aAB3NxN4JT,iv:utH50oFNdHofGrft8QT+0FcWyG+aIFeHBOXt51uV3mA=,tag:wW12GwxYJTby+UIscVztZg==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:B34bDf2NZOXYAvlnhzgZ2n7qrXIWbuEsdR2kwJbcQfCwdpY4a+UuxxQOeP45P2sEXGE=,iv:2xEDNACMn+8BoAZJEVib4Eo8eR5KHWyg3ITOArhbd/E=,tag:zrNc29hT/D2uheT4fEhRgw==,type:str]
    #ENC[AES256_GCM,data:yp+BodT6Ucjq+im2REUSW8Tn75Ym3MmJaUFveAzSGB9uAnopdDgGs6k=,iv:T128GHsy6hFGhSbZPtE0bWxXE5ldoO7e9qDisBeViVQ=,tag:q42YeC52Od/dgl2UYWb50A==,type:comment]
    #ENC[AES256_GCM,data:Y46K2Bvnp2hvBmY+QAwXORZoOYfd0axM+hMfZOzvho3SbJo3oOz8gXhUGG1r0G620eCxpuqutcc7um7qK+8kdedJnUZ/uQ==,iv:ftc2TOGbCwvsHuqldh79E4qf+6DbLKu6ezVElHZzMqs=,tag:gfm+T/oSOcHO/P+SEUH4wQ==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RWUE5deIYwbR+ixqnHXKaw==,iv:7U5PF93mBuGLQkSoPYr8nlQPMIl0T0CXlWOPnobJYPw=,tag:hD9XBZz25AGLi6ITFMmzLQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:dwAEmh5s/YZME4D0CiYToPLR/3k4Y+0S/qq8CtE1Njs=,iv:7cJi/D2bEkTvrAGCJV3eB6aGkFKESpjtdDfJQQp8FvA=,tag:7BjdKaIQwq4Adez/sSM/lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd2NQd0RpdmZ4YlRRN01W
            c0ZMMUJqU3RuaHZpSUVNVzRNT3c4K0dxRm5RCmI3MDE1WnBsQTV6SEt3Zm8vOWQr
            TEI3VExDeUgyWmFXVko1NlhybCtZcEkKLS0tIG9LbEp6K25jekFYcVVRcHErdjQ4
            eVdObXlyYk9vYStWUG1wRkc0dEUwNjAKkWJgEmp5taimIRuxDDCTooJcxFSaB6m6
            rB45vsFMkvOr2fu4TYFrE381wNrH5Km/fxFlh85f0xLuTKvW3WQ9HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T13:16:35Z"
    mac: ENC[AES256_GCM,data:aTkI5Z+XgMMZ14gmSLE/nhTUJ+LcYJ2d3zvgKX3B7SksL79oPN3CAx1AhZYyObsZk6fUeMfGDtdAvutIViq9DPbXGctD13r4ruVEz7WH0dGhE2nfHQZofFN0ovdI9OfmLiw96zsAtSOpqqCUewgpp+uG+ADAldhX/XYLhbUBuhc=,iv:t79//gljmar2yIVzAGmPky/kpMlUrsguteV2Rjakyj0=,tag:cUDteU+7tEN3b+22OyPhpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
