---
name: "Flux Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**.yaml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        path: ["kubernetes"]
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@16b08d136f181b8d06eec7cfeb7d1b8ec8147f4b # main
        with:
          # Flux CLI version e.g. 2.0.0.
          # Defaults to latest stable release.
          version: 'latest'

          # Alternative download location for the Flux CLI binary.
          # Defaults to path relative to $RUNNER_TOOL_CACHE.
          bindir: ''
      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@92d3a538c009c3fec120fbf50f6ef33b3e0a569c # 8.4.0
        id: diff
        with:
          sources: home-kubernetes
          path: "${{ matrix.path }}"
          resource: "${{ matrix.resource }}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@ec328af66588ab8f77cdeb2c264f14aba45bbf59 # v3.12
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
