---
name: "Flux Diff"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**.yaml"]

jobs:
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        path: ["kubernetes"]
        resource: ["helmrelease", "kustomization"]
    steps:
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
        with:
          # Flux CLI version e.g. 2.0.0.
          # Defaults to latest stable release.
          version: 'latest'

          # Alternative download location for the Flux CLI binary.
          # Defaults to path relative to $RUNNER_TOOL_CACHE.
          bindir: ''
      - name: Diff Resources
        uses: allenporter/flux-local/action/diff@d4ebcae7ae08c8c8b8b7c1f515cf86759f9ca950 # 8.1.0
        id: diff
        with:
          sources: home-kubernetes
          path: "${{ matrix.path }}"
          resource: "${{ matrix.resource }}"

      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add comment
        uses: mshick/add-pr-comment@f102bb3ebc97eedd4e2a98a9e71e462cc257fe80 # v3.9.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message-id: "${{ github.event.pull_request.number }}/${{ matrix.path }}/${{ matrix.resource }}"
          message-failure: Diff was not successful
          message: |
            ```diff
            ${{ steps.diff.outputs.diff }}
            ```
